default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cur_trader_development

test:
  <<: *default
  database: cur_trader_test

production:
  url: <%= ENV['DATABASE_URL'] %>